// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetBackendStatus() {
  return window['go']['main']['App']['GetBackendStatus']();
}

export function IsWails() {
  return window['go']['main']['App']['IsWails']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}
