// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function GetBackendStatus():Promise<string>;

export function IsLegacyMode():Promise<boolean>;

export function IsWails():Promise<boolean>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<boolean>;

export function ShowSaveDialog(arg1:string):Promise<string>;
